# Utilizado sempre após o CI de Homologação for realizado
name: Homolagação (CD) - Update de código

on:
  workflow_dispatch:

jobs:
  update-homolog:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /home/univates/cm/homolog

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Copia docker-compose.yml e dump.sql para a pasta de homologação
        run: |
          cp $GITHUB_WORKSPACE/docker-compose.yml /home/univates/cm/homolog/
          cp $GITHUB_WORKSPACE/dump.sql /home/univates/cm/homolog/

      - name: Gera o arquivo .env
        run: |
          cat > .env << EOF
          DB_USER=${{secrets.DB_USER}}
          DB_HOST=${{secrets.DB_HOST}}
          DB_PORT=${{secrets.DB_PORT}}
          DB_NAME=${{secrets.DB_NAME}}
          DB_PASSWORD=${{secrets.DB_PASSWORD}}
          SECRET_SESSION_KEY=${{secrets.SECRET_SESSION_KEY}}
          EOF

      - name: Atualização do ambiente de Homologação (Rootless)
        run: |
          # 1. Configura a variável para o terminal saber onde está o Docker Rootless
          export DOCKER_HOST=unix:///run/user/1001/docker.sock

          echo "2. Fazendo login de forma segura no GHCR..."
          docker login ghcr.io -u ${{ github.actor }} --password-stdin <<< "${{ secrets.GITHUB_TOKEN }}"

          echo "3. Baixando a versão mais recente de homologação..."
          APP_TAG=homolog docker compose pull

          echo "4. Atualizando a aplicação..."
          APP_TAG=homolog docker compose up -d --remove-orphans

          echo "5. Limpeza de credenciais..."
          docker logout ghcr.io
