# Utilizado sempre após o CI de Homologação for realizado
name: Homolagação (CD) - Update de código

on:
  workflow_dispatch:

jobs:
  update-homolog:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /home/univates/CM/homolog

    steps:
      - name: Atualização do ambiente de Homologação (Rootless)
        run: |
          # 1. Configura a variável para o terminal saber onde está o Docker Rootless
          export DOCKER_HOST=unix:///run/user/1001/docker.sock

          echo "2. Fazendo login de forma segura no GHCR..."
          docker login ghcr.io -u ${{ github.actor }} --password-stdin <<< "${{ secrets.GITHUB_TOKEN }}"

          echo "3. Baixando a versão mais recente de homologação..."
          APP_TAG=homolog docker compose pull

          echo "4. Atualizando a aplicação..."
          APP_TAG=homolog docker compose up -d --remove-orphans

          echo "5. Limpeza de credenciais..."
          docker logout ghcr.io
