# Utilizado sempre após o CI de Homologação for realizado
name: Homolagação (CD) - Update de código

on:
  workflow_dispatch:

jobs:
  update-homolog:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /home/univates/cm/homolog

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Copia docker-compose.yml para a pasta de homologação
        run: |
          cp $GITHUB_WORKSPACE/docker-compose.yml .

      - name: Gera o arquivo .env
        run: |
          cat > .env << EOF
          DB_USER=${{secrets.DB_USER}}
          DB_HOST=${{secrets.DB_HOST}}
          DB_PORT=${{secrets.DB_PORT}}
          DB_NAME=${{secrets.DB_NAME}}
          DB_PASSWORD=${{secrets.DB_PASSWORD}}
          SECRET_SESSION_KEY=${{secrets.SECRET_SESSION_KEY}}
          EOF

      - name: Atualização do ambiente de Homologação
        run: |
          echo "1. Fazendo login de forma segura no GHCR..."
          docker login ghcr.io -u ${{ github.actor }} --password-stdin <<< "${{ secrets.GITHUB_TOKEN }}"

          echo "2. Baixando a versão mais recente de homologação..." # puxa para o local
          APP_TAG=homolog docker compose pull

          echo "3. Subindo apenas o container do banco de dados..."
          APP_TAG=homolog docker compose up -d db

          echo "4. Rodando migrations em um container temporário..."
          # O docker run cria um container temporário. Roda o scrip de migrations, atualiza o banco e se destrói (--rm).
          # O container oficial ainda não foi mexido
          APP_TAG=homolog docker compose run --rm app alembic upgrade head

          echo "5. Atualizando ambiente de homologação..."
          APP_TAG=homolog docker compose up -d --remove-orphans

          echo "6. Limpeza de credenciais..."
          docker logout ghcr.io
