name: Configurar VM zerada

on:
  workflow_dispatch:

jobs:
  setup-infraestrutura:
    runs-on: self-hosted

    steps:
      - name: Instalar dependências e configurar pastas
        run: |
          set -x

          echo "Atualizando lista de pacotes..."
          # A flag DEBIAN_FRONTEND=noninteractive previne que o apt-get trave pedindo confirmações visuais
          sudo DEBIAN_FRONTEND=noninteractive apt-get update -y

          echo "Instalando o Docker..."
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

          echo "Instalando o plugin do Docker Compose..."
          sudo apt-get install docker-compose-plugin -y

          echo "Adicionando o usuário ao grupo docker..."

          # Adiciona o usuário atual ao grupo docker (Não pede sudo mais tarde)
          sudo gpasswd -a $USER docker

          echo "Criando pastas dos ambientes HOMOLOG e PROD..."
          mkdir -p /home/univates/cm/homolog
          mkdir -p /home/univates/cm/prod

          echo "Ajustando as permissões das pastas..."
          sudo chown -R $USER:$USER /home/univates/cm/homolog
          sudo chown -R $USER:$USER /home/univates/cm/prod

          echo "Provisionamento concluído! A VM está pronta para receber os ambientes!"
